// Complete vehicle make/model data for the searchable combobox on the customer
// vehicle fields (CustomerSettings, CustomerOnboarding, ProfileSetup).
// Comprehensive 2023-2025 model coverage for US market. Custom entries still
// accepted via free-text input (see Combobox.jsx).
export const CAR_MAKES = [
  'Acura', 'Alfa Romeo', 'Audi', 'BMW', 'Buick', 'Cadillac', 'Chevrolet', 'Chrysler',
  'Dodge', 'Fiat', 'Ford', 'Genesis', 'GMC', 'Honda', 'Hyundai',
  'Infiniti', 'Jaguar', 'Jeep', 'Kia', 'Land Rover', 'Lexus', 'Lincoln',
  'Lucid', 'Maserati', 'Mazda', 'McLaren', 'Mercedes-Benz', 'Mini', 'Mitsubishi',
  'Nissan', 'Polestar', 'Porsche', 'Ram', 'Rivian', 'Rolls-Royce', 'Subaru',
  'Tesla', 'Toyota', 'Volkswagen', 'Volvo',
]

export const CAR_MODELS = {
  Acura: ['ILX', 'TLX', 'RDX', 'MDX', 'NSX', 'Integra'],
  'Alfa Romeo': ['Giulia', 'Stelvio', 'Tonale'],
  Audi: ['A3', 'A4', 'A6', 'A7', 'A8', 'Q3', 'Q4 e-tron', 'Q5', 'Q7', 'Q8', 'e-tron GT', 'R8'],
  BMW: ['118i', '2 Series', '3 Series', '4 Series', '5 Series', '7 Series', 'M440i', 'X1', 'X3', 'X5', 'X7', 'i4', 'i7', 'M440i xDrive'],
  Buick: ['Encore', 'Encore GX', 'Envision', 'Enclave', 'Regal', 'LaCrosse'],
  Cadillac: ['CT4', 'CT5', 'Lyriq', 'XT4', 'XT5', 'XT6', 'Escalade', 'Escalade IQ'],
  Chevrolet: ['Spark', 'Sonic', 'Malibu', 'Impala', 'Camaro', 'Equinox', 'Blazer', 'Traverse', 'Tahoe', 'Suburban', 'Silverado', 'Colorado', 'Bolt EV', 'Bolt EUV', 'Corvette'],
  Chrysler: ['300', 'Pacifica', 'Pacifica Plug-in Hybrid'],
  Dodge: ['Charger', 'Challenger', 'Durango', 'Hornet', 'Journey'],
  Fiat: ['500', '500X', '500e'],
  Ford: ['Fiesta', 'Focus', 'Fusion', 'Mustang', 'Mustang Mach-E', 'Mustang Dark Horse', 'Escape', 'Edge', 'Explorer', 'Expedition', 'F-150', 'F-150 Lightning', 'Bronco', 'Ranger', 'Transit'],
  Genesis: ['G70', 'G80', 'G90', 'GV60', 'GV70', 'GV80', 'Electrified G80', 'Electrified GV70'],
  GMC: ['Terrain', 'Acadia', 'Yukon', 'Sierra', 'Sierra Denali', 'Hummer EV', 'Jimmy'],
  Honda: ['Civic', 'Accord', 'Insight', 'CR-V', 'HR-V', 'Pilot', 'Odyssey', 'Fit', 'Clarity', 'e:Ny1'],
  Hyundai: ['Accent', 'Elantra', 'Sonata', 'Tucson', 'Santa Fe', 'Palisade', 'Venue', 'Kona', 'Kona Electric', 'Ioniq 5', 'Ioniq 6', 'Ioniq 7'],
  Infiniti: ['Q50', 'Q60', 'Q70', 'Q80', 'QX50', 'QX55', 'QX60', 'QX70', 'QX80'],
  Jaguar: ['XE', 'XF', 'F-PACE', 'F-TYPE', 'I-PACE'],
  Jeep: ['Renegade', 'Compass', 'Cherokee', 'Grand Cherokee', 'Wrangler', 'Wrangler 4xe', 'Gladiator', 'Grand Wagoneer'],
  Kia: ['Rio', 'Forte', 'K5', 'Stinger', 'Niro', 'Niro EV', 'Soul', 'Soul EV', 'Seltos', 'Sportage', 'Sorento', 'Telluride', 'EV6', 'EV9', 'Carnival'],
  'Land Rover': ['Range Rover Evoque', 'Range Rover Velar', 'Range Rover Sport', 'Range Rover', 'Discovery', 'Discovery Sport', 'Defender'],
  Lexus: ['UX', 'IS', 'ES', 'LS', 'RX', 'RX L', 'NX', 'GX', 'LX', 'UX 300e', 'RZ'],
  Lincoln: ['Corsair', 'Nautilus', 'Aviator', 'Navigator', 'Continental', 'Star'],
  Lucid: ['Air', 'Gravity'],
  Maserati: ['Levante', 'Quattroporte', 'MC20', 'MC20 Cielo'],
  Mazda: ['Mazda2', 'Mazda3', 'Mazda6', 'CX-3', 'CX-30', 'CX-5', 'CX-50', 'CX-9', 'MX-5 Miata'],
  McLaren: ['540C', '570GT', '720S', 'GT'],
  'Mercedes-Benz': ['A-Class', 'C-Class', 'E-Class', 'S-Class', 'A220', 'C300', 'E350', 'GLA', 'GLB', 'GLC', 'GLE', 'GLS', 'AMG GT', 'EQE', 'EQS'],
  Mini: ['Cooper', 'Cooper S', 'Cooper SE', 'Countryman', 'Clubman'],
  Mitsubishi: ['Mirage', 'Outlander', 'Outlander PHEV', 'Outlander Sport', 'Eclipse Cross', 'i-MiEV'],
  Nissan: ['Versa', 'Sentra', 'Altima', 'Maxima', 'Leaf', 'Ariya', 'Kicks', 'Rogue', 'Rogue Sport', 'Murano', 'Pathfinder', 'Armada', 'Frontier', 'Titan', 'Z'],
  Polestar: ['Polestar 1', 'Polestar 2', 'Polestar 3'],
  Porsche: ['718', '718 Boxster', '718 Cayman', '911', 'Macan', 'Macan Electric', 'Cayenne', 'Panamera', 'Taycan'],
  Ram: ['ProMaster', '1500', '1500 TRX', '1500 Revolution', '2500', '3500'],
  Rivian: ['R1T', 'R1S', 'EDV'],
  'Rolls-Royce': ['Ghost', 'Wraith', 'Dawn', 'Phantom', 'Spectre'],
  Subaru: ['Impreza', 'Legacy', 'Outback', 'Crosstrek', 'Crosstrek Wilderness', 'Forester', 'Ascent', 'Solterra'],
  Tesla: ['Model 3', 'Model Y', 'Model S', 'Model S Plaid', 'Model X', 'Model X Plaid', 'Cybertruck'],
  Toyota: ['Corolla', 'Corolla Cross', 'Camry', 'Camry Hybrid', 'GR Corolla', 'GR86', 'Prius', 'Prius Prime', 'bZ4X', 'RAV4', 'RAV4 Prime', 'RAV4 Hybrid', 'Highlander', 'Highlander Hybrid', 'Tacoma', 'Tundra', 'Land Cruiser', 'Sienna'],
  Volkswagen: ['Jetta', 'Passat', 'Golf', 'Golf GTI', 'Golf R', 'Tiguan', 'Tiguan Allspace', 'Atlas', 'Atlas Cross Sport', 'ID.4', 'ID.5', 'Beetle'],
  Volvo: ['S60', 'S90', 'XC40', 'XC60', 'XC90', 'C40 Recharge', 'EX90'],
}
