// Complete vehicle make/model data for the searchable combobox on the customer
// vehicle fields (CustomerSettings, CustomerOnboarding, ProfileSetup).
// Comprehensive 2023-2025 model coverage for US market. Custom entries still
// accepted via free-text input (see Combobox.jsx).
export const CAR_MAKES = [
  'Acura', 'Alfa Romeo', 'Audi', 'BMW', 'Buick', 'Cadillac', 'Chevrolet', 'Chrysler',
  'Dodge', 'Fiat', 'Ford', 'Genesis', 'GMC', 'Honda', 'Hyundai',
  'Infiniti', 'Jaguar', 'Jeep', 'Kia', 'Land Rover', 'Lexus', 'Lincoln',
  'Lucid', 'Maserati', 'Mazda', 'McLaren', 'Mercedes-Benz', 'Mini', 'Mitsubishi',
  'Nissan', 'Polestar', 'Porsche', 'Ram', 'Rivian', 'Rolls-Royce', 'Subaru',
  'Tesla', 'Toyota', 'Volkswagen', 'Volvo',
]

export const CAR_MODELS = {
  Acura: ['ILX', 'TLX', 'RDX', 'MDX', 'NSX', 'Integra'],
  'Alfa Romeo': ['Giulia', 'Stelvio', 'Tonale'],
  Audi: ['A3', 'A4', 'A6', 'A7', 'A8', 'Q3', 'Q4 e-tron', 'Q5', 'Q7', 'Q8', 'e-tron GT', 'R8'],
  BMW: ['118i', '2 Series', '3 Series', '4 Series', '5 Series', '7 Series', 'M440i', 'X1', 'X3', 'X5', 'X7', 'i4', 'i7', 'M440i xDrive'],
  Buick: ['Encore', 'Encore GX', 'Envision', 'Enclave', 'Regal', 'LaCrosse'],
  Cadillac: ['CT4', 'CT5', 'Lyriq', 'XT4', 'XT5', 'XT6', 'Escalade', 'Escalade IQ'],
  Chevrolet: ['Spark', 'Sonic', 'Malibu', 'Impala', 'Camaro', 'Equinox', 'Blazer', 'Traverse', 'Tahoe', 'Suburban', 'Silverado', 'Colorado', 'Bolt EV', 'Bolt EUV', 'Corvette'],
  Chrysler: ['300', 'Pacifica', 'Pacifica Plug-in Hybrid'],
  Dodge: ['Charger', 'Challenger', 'Durango', 'Hornet', 'Journey'],
  Fiat: ['500', '500X', '500e'],
  Ford: ['Fiesta', 'Focus', 'Fusion', 'Mustang', 'Mustang Mach-E', 'Mustang Dark Horse', 'Escape', 'Edge', 'Explorer', 'Expedition', 'F-150', 'F-150 Lightning', 'Bronco', 'Ranger', 'Transit'],
  Genesis: ['G70', 'G80', 'G90', 'GV60', 'GV70', 'GV80', 'Electrified G80', 'Electrified GV70'],
  GMC: ['Terrain', 'Acadia', 'Yukon', 'Sierra', 'Sierra Denali', 'Hummer EV', 'Jimmy'],
  Honda: ['Civic', 'Accord', 'Insight', 'CR-V', 'HR-V', 'Pilot', 'Odyssey', 'Fit', 'Clarity', 'e:Ny1'],
  Hyundai: ['Accent', 'Elantra', 'Sonata', 'Tucson', 'Santa Fe', 'Palisade', 'Venue', 'Kona', 'Kona Electric', 'Ioniq 5', 'Ioniq 6', 'Ioniq 7'],
  Infiniti: ['Q50', 'Q60', 'Q70', 'Q80', 'QX50', 'QX55', 'QX60', 'QX70', 'QX80'],
  Jaguar: ['XE', 'XF', 'F-PACE', 'F-TYPE', 'I-PACE'],
  Jeep: ['Renegade', 'Compass', 'Cherokee', 'Grand Cherokee', 'Wrangler', 'Wrangler 4xe', 'Gladiator', 'Grand Wagoneer'],
  Kia: ['Rio', 'Forte', 'K5', 'Stinger', 'Niro', 'Niro EV', 'Soul', 'Soul EV', 'Seltos', 'Sportage', 'Sorento', 'Telluride', 'EV6', 'EV9', 'Carnival'],
  'Land Rover': ['Range Rover Evoque', 'Range Rover Velar', 'Range Rover Sport', 'Range Rover', 'Discovery', 'Discovery Sport', 'Defender'],
  Lexus: ['UX', 'IS', 'ES', 'LS', 'RX', 'RX L', 'NX', 'GX', 'LX', 'UX 300e', 'RZ'],
  Lincoln: ['Corsair', 'Nautilus', 'Aviator', 'Navigator', 'Continental', 'Star'],
  Lucid: ['Air', 'Gravity'],
  Maserati: ['Levante', 'Quattroporte', 'MC20', 'MC20 Cielo'],
  Mazda: ['Mazda2', 'Mazda3', 'Mazda6', 'CX-3', 'CX-30', 'CX-5', 'CX-50', 'CX-9', 'MX-5 Miata'],
  McLaren: ['540C', '570GT', '720S', 'GT'],
  'Mercedes-Benz': ['A-Class', 'C-Class', 'E-Class', 'S-Class', 'A220', 'C300', 'E350', 'GLA', 'GLB', 'GLC', 'GLE', 'GLS', 'AMG GT', 'EQE', 'EQS'],
  Mini: ['Cooper', 'Cooper S', 'Cooper SE', 'Countryman', 'Clubman'],
  Mitsubishi: ['Mirage', 'Outlander', 'Outlander PHEV', 'Outlander Sport', 'Eclipse Cross', 'i-MiEV'],
  Nissan: ['Versa', 'Sentra', 'Altima', 'Maxima', 'Leaf', 'Ariya', 'Kicks', 'Rogue', 'Rogue Sport', 'Murano', 'Pathfinder', 'Armada', 'Frontier', 'Titan', 'Z'],
  Polestar: ['Polestar 1', 'Polestar 2', 'Polestar 3'],
  Porsche: ['718', '718 Boxster', '718 Cayman', '911', 'Macan', 'Macan Electric', 'Cayenne', 'Panamera', 'Taycan'],
  Ram: ['ProMaster', '1500', '1500 TRX', '1500 Revolution', '2500', '3500'],
  Rivian: ['R1T', 'R1S', 'EDV'],
  'Rolls-Royce': ['Ghost', 'Wraith', 'Dawn', 'Phantom', 'Spectre'],
  Subaru: ['Impreza', 'Legacy', 'Outback', 'Crosstrek', 'Crosstrek Wilderness', 'Forester', 'Ascent', 'Solterra'],
  Tesla: ['Model 3', 'Model Y', 'Model S', 'Model S Plaid', 'Model X', 'Model X Plaid', 'Cybertruck'],
  Toyota: ['Corolla', 'Corolla Cross', 'Camry', 'Camry Hybrid', 'GR Corolla', 'GR86', 'Prius', 'Prius Prime', 'bZ4X', 'RAV4', 'RAV4 Prime', 'RAV4 Hybrid', 'Highlander', 'Highlander Hybrid', 'Tacoma', 'Tundra', 'Land Cruiser', 'Sienna'],
  Volkswagen: ['Jetta', 'Passat', 'Golf', 'Golf GTI', 'Golf R', 'Tiguan', 'Tiguan Allspace', 'Atlas', 'Atlas Cross Sport', 'ID.4', 'ID.5', 'Beetle'],
  Volvo: ['S60', 'S90', 'XC40', 'XC60', 'XC90', 'C40 Recharge', 'EX90'],
}

// Model → Vehicle Type auto-detection. If model not listed, type stays unset.
export const MODEL_TO_TYPE = {
  // Sedans
  'ILX': 'Sedan', 'TLX': 'Sedan', 'Integra': 'Sedan',
  'Giulia': 'Sedan', 'A3': 'Sedan', 'A4': 'Sedan', 'A6': 'Sedan', 'A7': 'Sedan', 'A8': 'Sedan',
  '118i': 'Sedan', '3 Series': 'Sedan', '5 Series': 'Sedan', '7 Series': 'Sedan',
  'Accent': 'Sedan', 'Elantra': 'Sedan', 'Sonata': 'Sedan',
  'Q50': 'Sedan', 'Q60': 'Sedan',
  'XE': 'Sedan', 'XF': 'Sedan',
  'Jetta': 'Sedan', 'Passat': 'Sedan', 'A-Class': 'Sedan', 'C-Class': 'Sedan', 'E-Class': 'Sedan', 'S-Class': 'Sedan',
  'Mirage': 'Sedan',
  'Versa': 'Sedan', 'Sentra': 'Sedan', 'Altima': 'Sedan', 'Maxima': 'Sedan',
  'G70': 'Sedan', 'G80': 'Sedan', 'G90': 'Sedan',
  'IS': 'Sedan', 'ES': 'Sedan',
  'Corsair': 'Sedan', 'Nautilus': 'Sedan', 'Continental': 'Sedan',
  'Malibu': 'Sedan', 'Impala': 'Sedan',
  '300': 'Sedan',
  'Charger': 'Sedan',
  'Focus': 'Sedan', 'Fusion': 'Sedan',
  'Insight': 'Sedan',
  'Accord': 'Sedan', 'Civic': 'Sedan',
  'K5': 'Sedan', 'Rio': 'Sedan', 'Forte': 'Sedan',
  'Mazda3': 'Sedan', 'Mazda6': 'Sedan',
  'Model 3': 'Sedan', 'Model S': 'Sedan',
  'Corolla': 'Sedan', 'Camry': 'Sedan', 'Prius': 'Sedan',
  'S60': 'Sedan', 'S90': 'Sedan',
  'Stinger': 'Sedan',
  'Avanti': 'Sedan',
  'Electrified G80': 'Sedan',

  // SUVs
  'RDX': 'SUV', 'MDX': 'SUV',
  'Q3': 'SUV', 'Q4 e-tron': 'SUV', 'Q5': 'SUV', 'Q7': 'SUV', 'Q8': 'SUV',
  'Q1': 'SUV', 'X1': 'SUV', 'X3': 'SUV', 'X5': 'SUV', 'X7': 'SUV',
  'Encore': 'SUV', 'Encore GX': 'SUV', 'Envision': 'SUV',
  'Lyriq': 'SUV', 'XT4': 'SUV', 'XT5': 'SUV', 'XT6': 'SUV',
  'Equinox': 'SUV', 'Blazer': 'SUV', 'Traverse': 'SUV', 'Tahoe': 'SUV',
  'Tonale': 'SUV', 'Stelvio': 'SUV',
  'CR-V': 'SUV', 'HR-V': 'SUV', 'Pilot': 'SUV',
  'Tucson': 'SUV', 'Santa Fe': 'SUV', 'Palisade': 'SUV', 'Venue': 'SUV', 'Kona': 'SUV', 'Kona Electric': 'SUV',
  'QX50': 'SUV', 'QX55': 'SUV', 'QX60': 'SUV', 'QX70': 'SUV', 'QX80': 'SUV',
  'F-PACE': 'SUV',
  'Compass': 'SUV', 'Cherokee': 'SUV', 'Renegade': 'SUV',
  'Niro': 'SUV', 'Niro EV': 'SUV', 'Seltos': 'SUV', 'Sportage': 'SUV', 'Sorento': 'SUV', 'Telluride': 'SUV',
  'Range Rover Evoque': 'SUV', 'Range Rover Velar': 'SUV', 'Range Rover': 'SUV', 'Discovery': 'SUV', 'Discovery Sport': 'SUV',
  'RX': 'SUV', 'RX L': 'SUV', 'NX': 'SUV', 'GX': 'SUV', 'LX': 'SUV', 'UX': 'SUV',
  'Escape': 'SUV', 'Edge': 'SUV', 'Explorer': 'SUV', 'Mustang Mach-E': 'SUV',
  'Terrain': 'SUV', 'Acadia': 'SUV', 'Yukon': 'SUV',
  'GV60': 'SUV', 'GV70': 'SUV', 'GV80': 'SUV', 'Electrified GV70': 'SUV',
  'CX-3': 'SUV', 'CX-30': 'SUV', 'CX-5': 'SUV', 'CX-50': 'SUV', 'CX-9': 'SUV',
  'Outlander': 'SUV', 'Outlander PHEV': 'SUV', 'Outlander Sport': 'SUV', 'Eclipse Cross': 'SUV',
  'Rogue': 'SUV', 'Rogue Sport': 'SUV', 'Murano': 'SUV', 'Pathfinder': 'SUV',
  'Macan': 'SUV', 'Macan Electric': 'SUV', 'Cayenne': 'SUV',
  'Range Rover Sport': 'SUV',
  'Levante': 'SUV',
  'Aviator': 'SUV', 'Nautilus': 'SUV',
  'RAV4': 'SUV', 'RAV4 Prime': 'SUV', 'RAV4 Hybrid': 'SUV', 'Highlander': 'SUV', 'Highlander Hybrid': 'SUV', '4Runner': 'SUV',
  'XC40': 'SUV', 'XC60': 'SUV', 'XC90': 'SUV', 'C40 Recharge': 'SUV', 'EX90': 'SUV',
  'Soul': 'SUV', 'Soul EV': 'SUV',
  'GLA': 'SUV', 'GLB': 'SUV', 'GLC': 'SUV', 'GLE': 'SUV', 'GLS': 'SUV',
  'Hummer EV': 'SUV', 'Jimmy': 'SUV',
  'Model Y': 'SUV', 'Model X': 'SUV',
  'bZ4X': 'SUV',
  'Defender': 'SUV',
  'EQE': 'SUV', 'EQS': 'SUV',
  'Tiguan': 'SUV', 'Tiguan Allspace': 'SUV', 'Atlas': 'SUV', 'Atlas Cross Sport': 'SUV', 'ID.4': 'SUV', 'ID.5': 'SUV',
  'Enclave': 'SUV',
  'Ioniq 5': 'SUV', 'Ioniq 6': 'EV', 'Ioniq 7': 'SUV',
  'EV6': 'SUV', 'EV9': 'SUV',
  'Air': 'SUV',
  'Gravity': 'SUV',
  'e-tron GT': 'Coupe',

  // Trucks
  'F-150': 'Truck', 'F-150 Lightning': 'Truck', 'Ranger': 'Truck',
  'Silverado': 'Truck', 'Colorado': 'Truck',
  '1500': 'Truck', '2500': 'Truck', '3500': 'Truck',
  'Sierra': 'Truck', 'Sierra Denali': 'Truck',
  'Tacoma': 'Truck', 'Tundra': 'Truck',
  'Frontier': 'Truck',
  'R1T': 'Truck',
  'Gladiator': 'Truck',

  // Vans
  'Pacifica': 'Van', 'Pacifica Plug-in Hybrid': 'Van',
  'Odyssey': 'Van',
  'Sienna': 'Van',
  'Transit': 'Van',
  'ProMaster': 'Van',
  'Carnival': 'Van',

  // Coupes
  'Camaro': 'Coupe',
  'Mustang': 'Coupe', 'Mustang Dark Horse': 'Coupe',
  'Challenger': 'Coupe',
  '2 Series': 'Coupe', '4 Series': 'Coupe',
  'M440i': 'Coupe', 'M440i xDrive': 'Coupe',
  'Z': 'Coupe',
  'GR86': 'Coupe',
  'Corvette': 'Coupe',
  '718': 'Coupe', '718 Boxster': 'Coupe', '718 Cayman': 'Coupe', '911': 'Coupe',
  'F-TYPE': 'Coupe',
  'Golf GTI': 'Coupe', 'Golf R': 'Coupe',
  'Beetle': 'Coupe', 'Golf': 'Coupe',
  'MX-5 Miata': 'Coupe',
  'GR Corolla': 'Coupe',
  'AMG GT': 'Coupe',
  '318i': 'Coupe',
  'Panamera': 'Coupe',
  'Ghost': 'Coupe', 'Wraith': 'Coupe', 'Phantom': 'Coupe',
  'I-PACE': 'Coupe',
  'Polestar 1': 'Coupe',

  // EVs
  'Leaf': 'EV',
  'Ariya': 'EV',
  'UX 300e': 'EV',
  'RZ': 'EV',
  'i4': 'EV', 'i7': 'EV',
  'Taycan': 'EV',
  'e:Ny1': 'EV',
  'Polestar 2': 'EV', 'Polestar 3': 'EV',
  '500e': 'EV',
  'Bolt EV': 'EV', 'Bolt EUV': 'EV',
  'Lucid': 'EV',
  'Solterra': 'EV',
  'Cybertruck': 'Truck',
  'Model 3': 'EV',
  'Model Y': 'EV',
  'Model S': 'EV',
  'Model S Plaid': 'EV',
  'Model X': 'EV',
  'Model X Plaid': 'EV',
  'i-MiEV': 'EV',
  'Clarity': 'EV',
}
